// Generated by scripts/page-dates.mjs. Do not edit.
export const PAGE_DATES = {
  "/": {
    "published": "2026-10-02T03:56:24+09:00",
    "modified": "2026-10-03T07:51:11+09:00",
    "hash": "d10c32bfaeef8af401a43e8881543e3bf3f66fedeb442ff74ca95976a831b320"
  },
  "/login": {
    "published": "2026-09-12T22:04:10+09:00",
    "modified": "2026-10-03T07:51:14+09:00",
    "hash": "b4b75ac797a58e35d12a849fada7166b28629bb5d0acfe89ad07bb0e31da378b"
  }
} as const;
