import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outFile = path.join(root, "src/lib/page-dates.generated.ts");

/** Page body each route's date follows. Hash these, not the generated file. */
const PAGES = [
  {
    route: "/",
    files: [
      "src/routes/index.tsx",
      "src/components/archive-app.tsx",
      "src/data/archive.ts",
    ],
  },
  {
    route: "/login",
    files: ["src/routes/login.tsx"],
  },
];

const watched = new Set(PAGES.flatMap((page) => page.files));

function rel(file) {
  return path.relative(root, file).split(path.sep).join("/");
}

export function isPageSource(file) {
  return watched.has(rel(file));
}

function readText(file) {
  const abs = path.join(root, file);
  return existsSync(abs) ? readFileSync(abs) : Buffer.alloc(0);
}

function hashFiles(files) {
  const hash = createHash("sha256");
  for (const file of files) {
    hash.update(file);
    hash.update("\0");
    hash.update(readText(file));
    hash.update("\0");
  }
  return hash.digest("hex");
}

function git(args) {
  try {
    return execFileSync("git", args, {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

function isDirty(files) {
  return git(["status", "--porcelain", "--", ...files]).length > 0;
}

function commitInstant(files) {
  return git(["log", "-1", "--format=%cI", "--", ...files]);
}

function saveInstant(files) {
  let latest = 0;
  for (const file of files) {
    const abs = path.join(root, file);
    if (!existsSync(abs)) continue;
    latest = Math.max(latest, statSync(abs).mtimeMs);
  }
  return latest ? new Date(latest).toISOString() : new Date().toISOString();
}

function toJst(instant) {
  const date = new Date(instant);
  if (Number.isNaN(date.getTime())) return toJst(new Date().toISOString());
  const shifted = new Date(date.getTime() + 9 * 60 * 60 * 1000);
  const pad = (n) => String(n).padStart(2, "0");
  return (
    `${shifted.getUTCFullYear()}-${pad(shifted.getUTCMonth() + 1)}-${pad(shifted.getUTCDate())}` +
    `T${pad(shifted.getUTCHours())}:${pad(shifted.getUTCMinutes())}:${pad(shifted.getUTCSeconds())}+09:00`
  );
}

function loadPrev() {
  if (!existsSync(outFile)) return {};
  const text = readFileSync(outFile, "utf8");
  const match = text.match(/export const PAGE_DATES = (\{[\s\S]*\}) as const/);
  if (!match) return {};
  try {
    return JSON.parse(match[1]);
  } catch {
    return {};
  }
}

export function stampPageDates() {
  const prev = loadPrev();
  const next = {};
  for (const page of PAGES) {
    const hash = hashFiles(page.files);
    const old = prev[page.route];
    if (old && old.hash === hash && old.published && old.modified) {
      next[page.route] = {
        published: old.published,
        modified: old.modified,
        hash,
      };
      continue;
    }
    const instant = isDirty(page.files)
      ? saveInstant(page.files)
      : commitInstant(page.files) || saveInstant(page.files);
    const modified = toJst(instant);
    next[page.route] = {
      published: old?.published || modified,
      modified,
      hash,
    };
  }
  const body =
    "// Generated by scripts/page-dates.mjs. Do not edit.\n" +
    "export const PAGE_DATES = " +
    JSON.stringify(next, null, 2) +
    " as const;\n";
  if (!existsSync(outFile) || readFileSync(outFile, "utf8") !== body) {
    writeFileSync(outFile, body);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  stampPageDates();
}
